version: '3'

services:
  backend:
    build: ./
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - my-network
    env_file:
      - ./backend/.env
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 8080:8080
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
